apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipa
  template:
    metadata:
      labels:
        app: shipa
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      terminationGracePeriodSeconds: 60
      containers:
      - name: shipa
        image: shipa:1.0
        ports:
        - name: shipa
          containerPort: 3000
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: shipa
spec:
  selector:
    service: shipa
  ports:
  - name: shipa
    port: 3000
    targetPort: shipa